// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmqkpsopasvznyzfixma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptcWtwc29wYXN2em55emZpeG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMzkxNTMsImV4cCI6MjA2MzgxNTE1M30.db0fyi6pgqaF_f_9-2ZFA_wxwV4jPzPdceVtsr2IRIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);